spring.application.name=investment
market-data.yahoo-base-url=https://query1.finance.yahoo.com
market-data.zf-bt-euro-clasic-url=https://www.zf.ro/fonduri-mutuale/fonduri-diversificate/bt-euro-clasic-14501383-fond
spring.cache.type=caffeine
spring.cache.cache-names=prices
spring.cache.caffeine.spec=maximumSize=256,expireAfterWrite=3h,recordStats
